class Award##first_tech##(RuleBase):

    div = ##div##
    name="##up_tech## R&D Award"
    desc="A point is awarded for each %s ##up_tech## vehicles sold." % div
    area="##lc_tech##"
    points="variable"

    #auto generated by fab make_rule
    @classmethod
    def run_rule(cls):
        for vp in VehicleProducer.objects.all():

            edit -> kwargs={'seller':vp,'vehicle__drivetrain__##lc_tech##':True}

            points=VehicleTransaction.points_since_last_turn(cls.div, **kwargs)

            if points > 0:
                RandDPointRecord.record(cls.name,vp,points,area=cls.area)